language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: "rake spec"
env:
  - PUPPET_VERSION=3.1.0 FACTER_VERSION=1.7.6
  - PUPPET_VERSION=3.4.0 FACTER_VERSION=2.0.2
  - PUPPET_VERSION=3.6.0 FACTER_VERSION=2.1.0
  - PUPPET_VERSION=3.6.0 FACTER_VERSION=2.1.0 STRICT_VARIABLES=yes

  # This are not necessarily the versions of facter that corespond with puppet
notifications:
  email:
    recipients:
      - owenspencer@gmail.com
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4b804b8a7908354e4b64
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
gemfile: Gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.1.0 FACTER_VERSION=1.7.6 #https://github.com/travis-ci/travis-ci/issues/1237
